name: Cypress API Tests
on:
    pull_request:
        branches: [master]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar o projeto
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                node-version: 20.9.0

            - name: Install dependencies
              run: npm install

            - name: Cypress run
              uses: cypress-io/github-action@v6
              